name: pre-commit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual start'
        required: false
        default: 'Manual checking'

jobs:
  pre-commit:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
      - name: Print manual run reason
        if: github.event_name == 'workflow_dispatch'
        run: echo "Reason for manual start - ${{ github.event.inputs.reason }}"
